LINKER=ar
CC=g++
INCLUDE=-I./include/
CFLAGS=-std=c++17 -Wall -pedantic $(INCLUDE)
SOURCES=$(shell find -name "*.cpp" | sed 's/\.\///')
OBJFILES=$(SOURCES:.cpp=.o)
LIBRARY=libimpl.a
LIBFLAGS=-rcs
DEPS=$(OBJFILES:.o=.dep)

all:$(BINARY)

ifneq ($(MAKECMDGOALS), clean)
ifneq ($(MAKECMDGOALS), purge)
-include $(DEPS)
endif
endif

all:$(LIBRARY)
	@echo "Moving library to root libs directory"; \
	mv $(LIBRARY) ../lib

$(LIBRARY):$(OBJFILES)
	@echo "Linking $(BINARY)"; \
	${LINKER} ${LIBFLAGS} ${LIBRARY} ${OBJFILES}

%.dep:%.cpp
	@echo "Generating dependencies for $<"; \
	$(CC) $(CFLAGS) -MM $< -MF $*.dep
	
%.o:%.cpp
	@echo "Compiling $@"; \
	$(CC) -c  $(CFLAGS) $< -o $@ 
	
clean:
	rm -rf *.o *.dep
	
purge:clean
	rm -rf ../libs/${LIBRARY}


